[package]
name = "asm8051_parser"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
chumsky = "*"
regex = "*"
string-join = "*"
ropey =  { version = "*", features = ["unicode_lines"] }
ahash = "*"
lazy_static = "1.4.0"
validate_issue_codes = { path = "macros/validate_issue_codes" }

[dev-dependencies]
test-case = "*"
