[package]
name = "asm8051_parser"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
chumsky = "*"
string-join = "*"
ropey =  { version = "*", features = ["unicode_lines"] }
ahash = "*"

[dev-dependencies]
test-case = "*"
