[package]
name = "load_documentation"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0.33"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
include_dir = "0.7.2"
