[package]
name = "load_documentation"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0.33"
serde = "*"
serde_json = "*"
include_dir = "0.7.2"
